# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name01', models.CharField(max_length=30)),
                ('name02', models.CharField(max_length=30)),
                ('name03', models.CharField(max_length=30)),
                ('name04', models.CharField(max_length=30)),
                ('name05', models.CharField(max_length=30)),
                ('name06', models.CharField(max_length=30)),
                ('name07', models.CharField(max_length=30)),
                ('name08', models.CharField(max_length=30)),
                ('name09', models.CharField(max_length=30)),
                ('name10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('cat01', models.BooleanField()),
                ('cat02', models.BooleanField()),
                ('cat03', models.BooleanField()),
                ('cat04', models.BooleanField()),
                ('cat05', models.BooleanField()),
                ('cat06', models.BooleanField()),
                ('cat07', models.BooleanField()),
                ('cat08', models.BooleanField()),
                ('cat09', models.BooleanField()),
                ('cat10', models.BooleanField()),
            ],
        ),
    ]
