# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20160620_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contents',
            field=models.TextField(default='study.detail', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
