# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20160701_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timeline',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline'),
        ),
        migrations.AddField(
            model_name='study',
            name='timeline',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline'),
        ),
        migrations.RunSQL(
            "INSERT INTO timeline_timeline (owner_id) SELECT id FROM auth_user ORDER BY id;"
        ),
        migrations.RunSQL(
            "UPDATE timeline_study SET timeline_id = (SELECT id FROM timeline_timeline WHERE owner_id = user_id LIMIT 1);"
        ),
        migrations.RunSQL(
            "UPDATE timeline_category SET timeline_id = (SELECT id FROM timeline_timeline WHERE owner_id = user_id LIMIT 1);"
        ),
    ]
