# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0009_auto_20160705_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='followers',
        ),
        migrations.AddField(
            model_name='timeline',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
