# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20160707_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestStudy',
            fields=[
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'proxy': True,
            },
            bases=('timeline.study',),
        ),
        migrations.AddField(
            model_name='study',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='studypic'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
