# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 13:36
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('timeline', '0012_auto_20160719_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='study',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=timeline.models.user_directory_path),
        ),
    ]
